version: '3.4'

services:
  samba:
    build: .
    restart: always
    environment:
      TZ: 'EST5EDT'
    # expose:
      # - 137
      # - 138
      # - 139
      # - 445
    ports:
      - '22445:22'
    stdin_open: true
    tty: true
    volumes:
      - './data/mnt:/data:z'
      - './ssh/authorized_keys:/root/.ssh/authorized_keys:ro'
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
